### ISSUE TITLE
Xeon (Beta) 1.2-beta3 Not Working

### ISSUE THREAD

**Issue by KeyFlyz** [peterprd/Xeon#18]
iPhone 8+ IOS 12.0.1 when I install this tweak the only thing that works is custom carrier text no images will work or anything else. very disappointed that this is marked compatible with my device.

**Comment by s8ngyu** [comment]
Do you have any crash logs?

**Comment by KeyFlyz** [comment]
Its not crashing when I try to set a gif as the carrier it just doesn’t work the only option I could get to work was custom carrier text everything else didn’t do anything.

**Comment by s8ngyu** [comment]
I'm facing that issue, too. I'm working on that.
