### ISSUE TITLE
Xeon - unc0ver problem

### ISSUE THREAD

**Issue by Xador123** [peterprd/Xeon#5]
Xeon blocks the unc0ver jailbreak option "Reload System Daemons" When Xeon is uninstalled unc0ver works again.

**Comment by s8ngyu** [comment]
I will install Xeon first when the A12 jailbreak drops, and If the issues exist, I'll look into it. and are you using RocketBoostrap 1.0.7?

**Comment by Xador123** [comment]
Yes, I always have the latest RocketBoostrap 1.07.
I have already confirmed a lot of users.
This is also just an info for You.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: PeterDev <notifications@github.com>
Gesendet: Thursday, March 21, 2019 1:48:33 PM
An: peterprd/Xeon
Cc: Xador123; Author
Betreff: Re: [peterprd/Xeon] Xeon - unc0ver problem (#5)


I will install Xeon first when the A12 jailbreak drops, and If the issues exist, I'll look into it. and are you using RocketBoostrap 1.0.7?

**Comment by s8ngyu** [comment]
Then, maybe It's a problem with HBPreferences. I heard that the tweak which using HBPreferences cause this issue.

**Comment by s8ngyu** [comment]
The problem of RocketBootstrap and HBPreferences.
